# Generated by Django 4.2.1 on 2023-05-18 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_comment_customer_id_alter_comment_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='stars',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='stars',
            old_name='product_id',
            new_name='product',
        ),
    ]
