# Generated by Django 4.2.1 on 2023-05-18 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category_alter_product_image_and_more'),
        ('reviews', '0004_alter_comment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stars',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_stars', to='products.product'),
        ),
    ]
